apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: lanches-caieiras
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | toString | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | toString | b64enc }}
  MERCADOPAGO_CLIENT_ID: {{ .Values.app.mercadopago.clientId | toString | b64enc }}
  MERCADOPAGO_SECRET_ID: {{ .Values.app.mercadopago.secretId | toString | b64enc }}
  MERCADOPAGO_POS_ID: {{ .Values.app.mercadopago.posId | toString | b64enc }}
