server:
  port: 8080

spring:
  application:
    name: Lanches Caieiras
  datasource:
    url: "${POSTGRES_JDBC}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

lncr:
  base-url: "${LNCR_BASE_URL}"

  integration:
    food-items-url: "${lncr.base-url}/foodItems"
    customers-url: "${lncr.base-url}/customers"
    customer-order-url: "${lncr.base-url}/customerOrders"
    kitchen-order-url: "${lncr.base-url}/kitchenOrders"
    payment-url: "${lncr.base-url}/payments/mercadoPago"


  customer:
    location-prefix: "${lncr.base-url}/customers"

  customer-order:
    location-prefix: "${lncr.base-url}/customerOrders"

  food-item:
    location-prefix: "${lncr.base-url}/foodItems"

  food-item-image:
    location-prefix: "${lncr.base-url}/foodItems/image"
    directory: "./images/"
    maxSize: 524288 # 512 KB
    extensions:
      ".jpg": "FFD8"
      ".png": "89504E47"

  kitchen-order:
    location-prefix: "${lncr.base-url}/kitchenOrders"

  mercadopago:
    location-prefix: "${lncr.base-url}/payments/mercadoPago"
    callbackUrl: "${MERCADOPAGO_CALLBACK_URL}" #Webhook para notificação de pagamento
    chargeUrl: "${MERCADOPAGO_QRCODE_URL}"
    paymentUrl: "${MERCADOPAGO_PAYMENTS_URL}"
    accessToken: "${MERCADOPAGO_ACCESS_TOKEN}" #.env
    userId: "${MERCADOPAGO_USER_ID}" #.env
    posId: "${MERCADOPAGO_POS_ID}" #.env
    mercado-pago-mock: false
    mercado-pago-mock-customer-order-id: 1