server:
  port: 8080

spring:
  application:
    name: Lanches Caieiras
  jackson:
    default-property-inclusion: non_null
  datasources:
    postgres:
      url: "${POSTGRES_JDBC}"
      jdbcUrl: "${POSTGRES_JDBC}"
      username: "${POSTGRES_USER}"
      password: "${POSTGRES_PASSWORD}"
      driver-class-name: org.postgresql.Driver
    h2:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
      console:
        enabled: true
        path: /h2-console
  #jpa: #Configurações do JPA estão definidas no arquivo br.com.tp.lanchescaieiras.commons.config.JPAConfig.java
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true

lncr:
  base-url: "${LNCR_BASE_URL}"

  integration:
    customers-url: "${lncr.base-url}/customers"
    customers-list-url: "${lncr.base-url}/customers/customerIdList"
    customer-orders-url: "${lncr.base-url}/customerOrders"
    food-items-url: "${lncr.base-url}/foodItems"
    food-items-list-url: "${lncr.base-url}/foodItems/foodItemListIds"
    kitchen-orders-url: "${lncr.base-url}/kitchenOrders"
    payments-url: "${lncr.base-url}/payments/mercadoPago"
    notification-url: "${lncr.base-url}/notifications"


  customer:
    location-prefix: "${lncr.base-url}/customers"

  customer-order:
    location-prefix: "${lncr.base-url}/customerOrders"

  food-item:
    location-prefix: "${lncr.base-url}/foodItems"
    max-images: 5
    image:
      location-prefix: "${lncr.base-url}/foodItems/image"
      directory: "./images/"
      maxSize: 524288 # 512 KB
      allowed-extensions:
        ".jpg": "FFD8"
        ".png": "89504E47"

  kitchen-order:
    location-prefix: "${lncr.base-url}/kitchenOrders"

  mercadopago:
    location-prefix: "${lncr.base-url}/payments/mercadoPago"
    oauth-url: "${MERCADOPAGO_OAUTH_URL}"
    orders-url: "${MERCADOPAGO_ORDERS_URL}"
    client-id: "${MERCADOPAGO_CLIENT_ID}"
    secret-id: "${MERCADOPAGO_SECRET_ID}"#.env
    pos-id: "${MERCADOPAGO_POS_ID}" #.env
    expiration-time: PT1H # 1 hora

  notification:
    location-prefix: "${lncr.base-url}/notifications"
