server:
  port: 8080
spring:
  application:
    name: Lanches Caieiras
  datasource:
    url: jdbc:postgresql://localhost:5432/db-lanches-caieiras
    username: lncr-admin
    password: Lncr$1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
lncr:
  customer:
    location-prefix: "https://localhost:8080/customers"
  food-item:
    location-prefix: "https://localhost:8080/foodItems"
  food-item-image:
    location-prefix: "https://localhost:8080/foodItems/image"
    directory: "../storage/images/"
    maxSize: 524288 # 512 KB
    extensions:
      ".jpg": "FFD8"
      ".png": "89504E47"
