apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-nlb
  labels:
    app: {{ .Values.app.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.nlb.port }}
      targetPort: {{ .Values.service.nlb.targetPort }}
      protocol: {{ .Values.service.nlb.protocol }}
      name: {{ .Values.service.nlb.name }}
  selector:
    app: {{ .Values.app.name }}