openapi: 3.0.1
info:
  title: Lanchonete Caieiras
  description: 'Gerenciador de Pedidos, Ordem de Preparo, Produtos e Pagamento'
  contact: 
    email: titoparizotto@gmail.com
    name: Tito de Morais Parizotto
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/lanchoneteCaieiras/v1'
tags:
  - name: CollectionOperations
    description: Operações que utilizam arquétipo Coleções
  - name: ManagedOperations
    description: Operações que utilizam arquétipo Gerenciável
paths:
  '/customers':
    post:
      operationId: createCustomer
      description: Criar um novo cliente
      summary: Criar um novo cliente
      tags:
        - CollectionOperations
      requestBody:
        $ref: '#/components/requestBodies/CreateCustomer'
      responses:
        '201':
          $ref: '#/components/responses/CreatedCustomer'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
           $ref: '#/components/responses/ConflictCustomer'
        '500':
          $ref: '#/components/responses/InternalServerError'
    get:
      operationId: listCustomers
      description: Lista de clientes
      summary: Listar clientes com de filtros
      tags:
        - CollectionOperations
      parameters:
        - $ref: '#/components/parameters/Status'
        - $ref: '#/components/parameters/LimitTemplate'
      responses:
        '200': 
          $ref: '#/components/responses/ListCustomersOK'
        '400': 
           $ref: '#/components/responses/BadRequest'
        '500': 
           $ref: '#/components/responses/InternalServerError'
           
  '/customer/{customerDocument}':
    get:
      operationId: getCustomer
      description: Obter um cliente pelo documento
      summary: Obter informações de um cliente pelo documento
      tags:
        - ManagedOperations
      parameters:
        - $ref: '#/components/parameters/GetCustomerDocument'
      responses:
        '200': 
          $ref: '#/components/responses/GetCustomerOk'
        '404': 
          $ref: '#/components/responses/NotFound'
        '500': 
          $ref: '#/components/responses/InternalServerError'
    patch:
      operationId: getCustomer
      description: Obter um cliente pelo documento
      summary: Obter informações de um cliente pelo documento (CPF)
      tags:
        - ManagedOperations
      parameters:
        - $ref: '#/components/parameters/GetCustomerDocument'
      requestBody:
        $ref: '#/components/requestBodies/PartialUpdateCustomer'
      responses:
        '200': 
          $ref: '#/components/responses/GetCustomerOk'
        '404': 
          $ref: '#/components/responses/NotFound'
        '500': 
          $ref: '#/components/responses/InternalServerError'

components:
  requestBodies:
    CreateCustomer:
      description: Criar Cliente request body
      content: 
        application/json:
          schema: 
            $ref: '#/components/schemas/CreateCustomerType'
          examples: 
            201-CreateCustomer:
              summary: Criação de Cliente
              value:
                documentNumber: 1111111111
                name: José da Silva
                e-mail: josedasilva@email.com
                
            400-BadRequestWithoutFields:
              summary: Campos faltantes
              value:
                name: José da Silva
                e-mail: josedasilva@email.com
            
           
    
    PartialUpdateCustomer:
      description: Atualizar informações parciais do cliente
      content: 
        application/json:
          schema: 
            $ref: '#/components/schemas/PartialUpdateCustomerType'
          examples: 
            201-Created:
              summary: Cliente criado com sucesso
              value: 
                documentNumber: "11111111111"
                name: Jose da Silva
                email: josedasilve@gmail.com
                status: Activate
            400-BadRequestWithoutDocumentNumber:
              summary: Criação sem campo de CPF
              value:
                name: Jose da Silva
                email: josedasilve@gmail.com
                status: Activate
            500-InternalServerError:
              summary: Internal server error
              value: 
                documentNumber: "11111111111"
                name: Jose da Silva*
                email: josedasilve@gmail.com
                status: Activate
    
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseTemplate'
          examples:
            RegistrationNumberWrongFormat:
              summary: Erro de formato inválido
              value:
                response:
                  _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                  _timestamp: '2025-02-12T21:41:43.286Z'
    
    ConflictCustomer:
      description: Conflict Customer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseTemplate'
          examples:
            RegistrationNumberWrongFormat:
              summary: Documento já utilizado 
              value:
                response:
                  _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                  _timestamp: '2025-02-12T21:41:43.286Z'
                  _message: Documento informado já foi utilizado.
                  
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseTemplate'
          examples:
            RegistrationNumberWrongFormat:
              summary: Erro Interno
              value:
                response:
                  _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                  _timestamp: '2025-02-12T21:41:43.286Z'
                  
    
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseTemplate'
          examples:
            RegistrationNumberWrongFormat:
              summary: Recurso não encontrado
              value:
                response:
                  _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                  _timestamp: '2025-02-12T21:41:43.286Z'
                  

    CreatedCustomer:
      description: Cliente criado com sucesso
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseTemplate'
          examples:
            201-Created:
              summary: Cliente criado com sucesso
              value:
                response:
                    _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                    _timestamp: '2025-02-12T21:41:43.286Z'
                customerId: 1    
                status: Activate
      headers:
        Location:
          $ref: '#/components/headers/Location'
    
    GetCustomerOk:
      description: Informação de cliente por documento (CPF)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetCustomerType'
          examples:
            200-GetCustomerOk:
              summary: Cliente localizadocom sucesso
              value:
                response:
                    _traceId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
                    _timestamp: '2021-02-11T21:41:43.286Z'
                customerId: 1
                documentNumber: "11111111111"
                name: Jose da Silva
                email: josedasilve@gmail.com
                status: Activate
    
    ListCustomersOK:
      description: Lista de clientes retornadas com sucesso.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListCustomersType'
            
    
    
    
  parameters: 
    GetCustomerDocument:
      name: customerDocument
      in: path
      required: true
      description: Identificador único do cliente
      schema:
        $ref: '#/components/schemas/CustomerDocumentType'
    
    Status:
      name: 'status'
      in: query
      description: Status do registros a serem retornados
      required: false
      schema:
        $ref: '#/components/schemas/StatusType'
  
    LimitTemplate:
      name: '_limit'
      in: query
      description: Quantidade limite de registros retornados
      required: false
      schema:
        $ref: '#/components/schemas/LimitTemplate'
      
  headers:
    Location:
      description: URI do recuros
      required: true
      schema:
        type: string
        format: uri
      
  schemas:
    CreateCustomerType:
      allOf:
        - $ref: '#/components/schemas/CustomerTemplate'
        - required:
            - documentNumber
            - name
            - email
            
    PartialUpdateCustomerType:
      description: Atualiza informações
      allOf:
        - $ref: '#/components/schemas/CustomerTemplate'
        

    CustomerDocumentType:
      description: User unique id
      allOf:
        - $ref: '#/components/schemas/CustomerTemplate/properties/documentNumber'
        - required:
            - documentNumber
            
    GetCustomerType:
      description: Informação de um cliente
      allOf:
        - $ref: '#/components/schemas/ResponseTemplate'
        - $ref: '#/components/schemas/CustomerTemplate'
        
      
          
    

    ListCustomersType:
      description: Lista de clientes
      allOf:
        - $ref: '#/components/schemas/ResponseTemplate'
        - type: object
      properties:
        data:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/CustomerTemplate'
              - type: object
                required:
                  - documentNumber
                  - name
                  - email

    
    StatusType:
      description: Informação de status do recurso 
      type: string
      enum:
        - Activate
        - Inactive
    
    
    
    LimitTemplate:
      description: Número de registros p
      type: integer
      minimum: 1
      exclusiveMinimum: false
      maximum: 50 
      default: 10
    
    ResponseTemplate:
      description: Modelo de dados para responses
      type: object
      properties:
        response:
          type: object
          properties:
            _traceId:
              type: string
              description: UUID gerado para rastreabilidade da transação
              format: uuid
            _timestamp:
              type: string
              description: Timestamp da transação
              format: date-time
            _message:
              type: string
              description: Menssagem de resposta
              maxLength: 50
            _code:
              type: integer
              description: Código específico de resposta
              minimum: 0
    
    CustomerTemplate:
      description: Modelo de dados do cliente
      type: object
      properties:
        customerId:
          description: Id único do cliente
          type: integer
          readOnly: true
          minimum: 1
          maximum: 9999
          format: int32
        documentNumber:
          description: Numero do documento do CPF do Cliente
          type: string
          minLength: 11
          maxLength: 11
        name:
          description: Nome do Cliente
          type: string
          minLength: 1
          maxLength: 255
        email:
          description: E-mail do Cliente
          type: string
          minLength: 1
          maxLength: 255    
        status:
          description: Status do Cliente
          type: string
          minLength: 1
          maxLength: 20   
            