name: Build and upload image
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build-and-upload:
    name: Build and Upload Docker image to ECR
    runs-on: codebuild-github-lncr-app-${{ github.run_id }}-${{ github.run_attempt }}
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    environment:
      name: ${{ github.ref_name == 'master' && 'prd' || 'dev' }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Set Paths and Env Variables
        id: set-vars
        run: |
          DOCKERFILE_PATH=$PWD/java/app/Dockerfile
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV
          echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image to ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG=${{ env.COMMIT_HASH }}
          
          # Build da imagem
          IMAGE_NAME=lncr-app-$IMAGE_TAG
          docker build -t $IMAGE_NAME -f $DOCKERFILE_PATH .
          
          # Tag da imagem para ECR
          docker tag $IMAGE_NAME $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $IMAGE_NAME $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Push das imagens
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          echo "Image built and pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        env:
          DOCKERFILE_PATH: ${{ env.DOCKERFILE_PATH }}
