name: Build and upload image
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
    types: [closed]

  workflow_dispatch:

jobs:
  build-and-upload:
    name: Build and Upload Docker image to ECR
    runs-on: codebuild-github-lncr-app-${{ github.run_id }}-${{ github.run_attempt }}
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: ${{ github.ref_name == 'master' && 'prd' || 'dev' }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Paths and Env Variables
        id: set-vars
        run: |
          DOCKERFILE_PATH=$PWD/app/Dockerfile
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV
          echo "commit-hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ env.COMMIT_HASH }}
          IMAGE_NAME=lncr-app-$IMAGE_TAG
          docker build -t $IMAGE_NAME -f $DOCKERFILE_PATH . \
          --build-arg LNCR_MAVEN_ACTOR=$LNCR_MAVEN_ACTOR \
          --build-arg LNCR_MAVEN_PAT=$LNCR_MAVEN_PAT \
          --build-arg DEBUG=$DEBUG
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        env:
          DOCKERFILE_PATH: ${{ env.DOCKERFILE_PATH }}
          LNCR_MAVEN_PAT: ${{ secrets.LNCR_MAVEN_PAT }}
          LNCR_MAVEN_ACTOR: ${{ secrets.LNCR_MAVEN_ACTOR }}
          DEBUG: ${{ vars.DEBUG }}

      - name: Tag image for ECR
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG=${{ env.COMMIT_HASH }}
          
          docker tag ${{ env.IMAGE_NAME }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV

      - name: Push image to ECR
        run: |
          IMAGE_TAG=${{ env.COMMIT_HASH }}
          
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          
          echo "Image pushed to ECR: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG"
        env:
          DOCKERFILE_PATH: ${{ env.DOCKERFILE_PATH }}
